#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyCF")]
	public partial class QLCFDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBan(Ban instance);
    partial void UpdateBan(Ban instance);
    partial void DeleteBan(Ban instance);
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertLoaiThucDon(LoaiThucDon instance);
    partial void UpdateLoaiThucDon(LoaiThucDon instance);
    partial void DeleteLoaiThucDon(LoaiThucDon instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThucDon(ThucDon instance);
    partial void UpdateThucDon(ThucDon instance);
    partial void DeleteThucDon(ThucDon instance);
    #endregion
		
		public QLCFDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLyCFConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLCFDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCFDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCFDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCFDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ban> Bans
		{
			get
			{
				return this.GetTable<Ban>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThucDon> LoaiThucDons
		{
			get
			{
				return this.GetTable<LoaiThucDon>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThucDon> ThucDons
		{
			get
			{
				return this.GetTable<ThucDon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ban")]
	public partial class Ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maBan;
		
		private string _trangThai;
		
		private System.Nullable<int> _maHoaDon;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaBanChanging(int value);
    partial void OnmaBanChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnmaHoaDonChanging(System.Nullable<int> value);
    partial void OnmaHoaDonChanged();
    #endregion
		
		public Ban()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="Int")]
		public System.Nullable<int> maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_HoaDon", Storage="_HoaDons", ThisKey="maBan", OtherKey="maBan")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.Ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChiTietHoaDon;
		
		private System.Nullable<int> _maHoaDon;
		
		private string _maThucDon;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<decimal> _thanhTien;
		
		private string _trangThai;
		
		private EntityRef<HoaDon> _HoaDon;
		
		private EntityRef<ThucDon> _ThucDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChiTietHoaDonChanging(int value);
    partial void OnmaChiTietHoaDonChanged();
    partial void OnmaHoaDonChanging(System.Nullable<int> value);
    partial void OnmaHoaDonChanged();
    partial void OnmaThucDonChanging(string value);
    partial void OnmaThucDonChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnthanhTienChanging(System.Nullable<decimal> value);
    partial void OnthanhTienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			this._ThucDon = default(EntityRef<ThucDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChiTietHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maChiTietHoaDon
		{
			get
			{
				return this._maChiTietHoaDon;
			}
			set
			{
				if ((this._maChiTietHoaDon != value))
				{
					this.OnmaChiTietHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maChiTietHoaDon = value;
					this.SendPropertyChanged("maChiTietHoaDon");
					this.OnmaChiTietHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="Int")]
		public System.Nullable<int> maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maThucDon
		{
			get
			{
				return this._maThucDon;
			}
			set
			{
				if ((this._maThucDon != value))
				{
					if (this._ThucDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThucDonChanging(value);
					this.SendPropertyChanging();
					this._maThucDon = value;
					this.SendPropertyChanged("maThucDon");
					this.OnmaThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="maHoaDon", OtherKey="maHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maHoaDon = value.maHoaDon;
					}
					else
					{
						this._maHoaDon = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucDon_ChiTietHoaDon", Storage="_ThucDon", ThisKey="maThucDon", OtherKey="maThucDon", IsForeignKey=true)]
		public ThucDon ThucDon
		{
			get
			{
				return this._ThucDon.Entity;
			}
			set
			{
				ThucDon previousValue = this._ThucDon.Entity;
				if (((previousValue != value) 
							|| (this._ThucDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThucDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._ThucDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maThucDon = value.maThucDon;
					}
					else
					{
						this._maThucDon = default(string);
					}
					this.SendPropertyChanged("ThucDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHoaDon;
		
		private System.Nullable<System.DateTime> _ngayThanhToan;
		
		private decimal _tongTienThanhToan;
		
		private string _trangThai;
		
		private System.Nullable<int> _maBan;
		
		private string _maNhanVien;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<Ban> _Ban;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(int value);
    partial void OnmaHoaDonChanged();
    partial void OnngayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayThanhToanChanged();
    partial void OntongTienThanhToanChanging(decimal value);
    partial void OntongTienThanhToanChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnmaBanChanging(System.Nullable<int> value);
    partial void OnmaBanChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._Ban = default(EntityRef<Ban>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayThanhToan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayThanhToan
		{
			get
			{
				return this._ngayThanhToan;
			}
			set
			{
				if ((this._ngayThanhToan != value))
				{
					this.OnngayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ngayThanhToan = value;
					this.SendPropertyChanged("ngayThanhToan");
					this.OnngayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTienThanhToan", DbType="Decimal(20,0) NOT NULL")]
		public decimal tongTienThanhToan
		{
			get
			{
				return this._tongTienThanhToan;
			}
			set
			{
				if ((this._tongTienThanhToan != value))
				{
					this.OntongTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._tongTienThanhToan = value;
					this.SendPropertyChanged("tongTienThanhToan");
					this.OntongTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maBan", DbType="Int")]
		public System.Nullable<int> maBan
		{
			get
			{
				return this._maBan;
			}
			set
			{
				if ((this._maBan != value))
				{
					if (this._Ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaBanChanging(value);
					this.SendPropertyChanging();
					this._maBan = value;
					this.SendPropertyChanged("maBan");
					this.OnmaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maHoaDon", OtherKey="maHoaDon")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ban_HoaDon", Storage="_Ban", ThisKey="maBan", OtherKey="maBan", IsForeignKey=true)]
		public Ban Ban
		{
			get
			{
				return this._Ban.Entity;
			}
			set
			{
				Ban previousValue = this._Ban.Entity;
				if (((previousValue != value) 
							|| (this._Ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ban.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._Ban.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maBan = value.maBan;
					}
					else
					{
						this._maBan = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private string _loaiNhanVien;
		
		private string _trangThai;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnloaiNhanVienChanging(string value);
    partial void OnloaiNhanVienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(80)")]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(20)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(MAX)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(20)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiNhanVien", DbType="NVarChar(50)")]
		public string loaiNhanVien
		{
			get
			{
				return this._loaiNhanVien;
			}
			set
			{
				if ((this._loaiNhanVien != value))
				{
					this.OnloaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._loaiNhanVien = value;
					this.SendPropertyChanged("loaiNhanVien");
					this.OnloaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThucDon")]
	public partial class LoaiThucDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoaiThucDon;
		
		private string _tenLoaiThucDon;
		
		private EntitySet<ThucDon> _ThucDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiThucDonChanging(string value);
    partial void OnmaLoaiThucDonChanged();
    partial void OntenLoaiThucDonChanging(string value);
    partial void OntenLoaiThucDonChanged();
    #endregion
		
		public LoaiThucDon()
		{
			this._ThucDons = new EntitySet<ThucDon>(new Action<ThucDon>(this.attach_ThucDons), new Action<ThucDon>(this.detach_ThucDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoaiThucDon
		{
			get
			{
				return this._maLoaiThucDon;
			}
			set
			{
				if ((this._maLoaiThucDon != value))
				{
					this.OnmaLoaiThucDonChanging(value);
					this.SendPropertyChanging();
					this._maLoaiThucDon = value;
					this.SendPropertyChanged("maLoaiThucDon");
					this.OnmaLoaiThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenLoaiThucDon
		{
			get
			{
				return this._tenLoaiThucDon;
			}
			set
			{
				if ((this._tenLoaiThucDon != value))
				{
					this.OntenLoaiThucDonChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiThucDon = value;
					this.SendPropertyChanged("tenLoaiThucDon");
					this.OntenLoaiThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThucDon_ThucDon", Storage="_ThucDons", ThisKey="maLoaiThucDon", OtherKey="maLoaiThucDon")]
		public EntitySet<ThucDon> ThucDons
		{
			get
			{
				return this._ThucDons;
			}
			set
			{
				this._ThucDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThucDons(ThucDon entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThucDon = this;
		}
		
		private void detach_ThucDons(ThucDon entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThucDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenTaiKhoan;
		
		private string _matKhau;
		
		private string _maNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenTaiKhoanChanging(string value);
    partial void OntenTaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenTaiKhoan
		{
			get
			{
				return this._tenTaiKhoan;
			}
			set
			{
				if ((this._tenTaiKhoan != value))
				{
					this.OntenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._tenTaiKhoan = value;
					this.SendPropertyChanged("tenTaiKhoan");
					this.OntenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThucDon")]
	public partial class ThucDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThucDon;
		
		private string _tenThucDon;
		
		private string _donViTinh;
		
		private System.Nullable<decimal> _donGia;
		
		private string _maLoaiThucDon;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<LoaiThucDon> _LoaiThucDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThucDonChanging(string value);
    partial void OnmaThucDonChanged();
    partial void OntenThucDonChanging(string value);
    partial void OntenThucDonChanged();
    partial void OndonViTinhChanging(string value);
    partial void OndonViTinhChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnmaLoaiThucDonChanging(string value);
    partial void OnmaLoaiThucDonChanged();
    #endregion
		
		public ThucDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._LoaiThucDon = default(EntityRef<LoaiThucDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThucDon
		{
			get
			{
				return this._maThucDon;
			}
			set
			{
				if ((this._maThucDon != value))
				{
					this.OnmaThucDonChanging(value);
					this.SendPropertyChanging();
					this._maThucDon = value;
					this.SendPropertyChanged("maThucDon");
					this.OnmaThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenThucDon
		{
			get
			{
				return this._tenThucDon;
			}
			set
			{
				if ((this._tenThucDon != value))
				{
					this.OntenThucDonChanging(value);
					this.SendPropertyChanging();
					this._tenThucDon = value;
					this.SendPropertyChanged("tenThucDon");
					this.OntenThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string donViTinh
		{
			get
			{
				return this._donViTinh;
			}
			set
			{
				if ((this._donViTinh != value))
				{
					this.OndonViTinhChanging(value);
					this.SendPropertyChanging();
					this._donViTinh = value;
					this.SendPropertyChanged("donViTinh");
					this.OndonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiThucDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maLoaiThucDon
		{
			get
			{
				return this._maLoaiThucDon;
			}
			set
			{
				if ((this._maLoaiThucDon != value))
				{
					if (this._LoaiThucDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiThucDonChanging(value);
					this.SendPropertyChanging();
					this._maLoaiThucDon = value;
					this.SendPropertyChanged("maLoaiThucDon");
					this.OnmaLoaiThucDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThucDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maThucDon", OtherKey="maThucDon")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThucDon_ThucDon", Storage="_LoaiThucDon", ThisKey="maLoaiThucDon", OtherKey="maLoaiThucDon", IsForeignKey=true)]
		public LoaiThucDon LoaiThucDon
		{
			get
			{
				return this._LoaiThucDon.Entity;
			}
			set
			{
				LoaiThucDon previousValue = this._LoaiThucDon.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThucDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThucDon.Entity = null;
						previousValue.ThucDons.Remove(this);
					}
					this._LoaiThucDon.Entity = value;
					if ((value != null))
					{
						value.ThucDons.Add(this);
						this._maLoaiThucDon = value.maLoaiThucDon;
					}
					else
					{
						this._maLoaiThucDon = default(string);
					}
					this.SendPropertyChanged("LoaiThucDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThucDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThucDon = null;
		}
	}
}
#pragma warning restore 1591
